/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalPages;

/**
 *
 * @author SCC COMPLAB
 */
public class dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        seatedit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tableres = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        time = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        calendar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seatedit.setBackground(new java.awt.Color(102, 0, 0));
        seatedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seateditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seateditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seateditMouseExited(evt);
            }
        });
        seatedit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pick Seat");
        seatedit.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        jPanel2.add(seatedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 170, 80));

        tableres.setBackground(new java.awt.Color(102, 0, 0));
        tableres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableresMouseExited(evt);
            }
        });
        tableres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Table Reservation");
        tableres.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        jPanel2.add(tableres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        time.setBackground(new java.awt.Color(102, 0, 0));
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeMouseExited(evt);
            }
        });
        time.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pick Time");
        time.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 170, 80));

        calendar.setBackground(new java.awt.Color(102, 0, 0));
        calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calendarMouseExited(evt);
            }
        });
        calendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Open Calendar");
        calendar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        jPanel2.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 190, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        jDesktopPane1.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seateditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seateditMouseClicked
        
    }//GEN-LAST:event_seateditMouseClicked

    private void seateditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seateditMouseEntered
        
    }//GEN-LAST:event_seateditMouseEntered

    private void seateditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seateditMouseExited
        
    }//GEN-LAST:event_seateditMouseExited

    private void tableresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseClicked
        
    }//GEN-LAST:event_tableresMouseClicked

    private void tableresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseEntered
        
    }//GEN-LAST:event_tableresMouseEntered

    private void tableresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseExited
        
    }//GEN-LAST:event_tableresMouseExited

    private void timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseClicked
        
    }//GEN-LAST:event_timeMouseClicked

    private void timeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseEntered
       
    }//GEN-LAST:event_timeMouseEntered

    private void timeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseExited
        
    }//GEN-LAST:event_timeMouseExited

    private void calendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseClicked
        
    }//GEN-LAST:event_calendarMouseClicked

    private void calendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseEntered
        
    }//GEN-LAST:event_calendarMouseEntered

    private void calendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseExited
        
    }//GEN-LAST:event_calendarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel seatedit;
    private javax.swing.JPanel tableres;
    private javax.swing.JPanel time;
    // End of variables declaration//GEN-END:variables
}
